### PR TITLE
Configurable seed entropy

### LINKED ISSUE #30: Option to select seed entropy
`SeedBitSize` is hardcoded to `128` bitsize
Make it configurable to support both `128` and `256`

### PR DESCRIPTION
**Pull request by briancaine**
Not done yet, but...: Fixes #30 

@evanlinjin I added a seedBitSize argument. Where do we want this value to be configurable? Is it a static value when the wallet is started up? Or is it an argument to the `/api/wallets/seed` API endpoint?

### CODE REVIEW

**Comment by therealssj** [comment]
This will be an argument to the endpoint

**Comment by briancaine** [comment]
Done.

**Comment by briancaine** [comment]
Will do that tomorrow.

**Comment by briancaine** [comment]
@therealssj Sorry about the delay. I got started on Friday but I got distracted.

Anyway, I kept the `SeedBitSizeFromString` tests as well. Those tests and the API endpoint tests largely overlap, but the `SeedBitSizeFromString` tests are a little more specific.

I can take them out if you'd prefer, but I don't see that function changing too much, so I don't think it's a huge deal to keep the additional tests in.

**Pull request merged**
